name: Run Azure Login with OIDC
on: 
  push:
    branches: 
      - 'main'
      - 'develop/**' 

permissions:
  id-token: write
  contents: read

env: 
  AZURE_WEBAPP_NAME: getting-started
  AZURE_WEBAPP_PACKAGE_PATH: '.\app'
  PIP_VERSION: '25.0.1'

jobs:
  login_to_azure:
    name: Checkout and Login to azure
    runs-on: ubuntu-latest
    environment: Production
    steps: 
      - uses: actions/checkout@main
      - uses: azure/login@v2 
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_TERRAFORM }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list