name: Trivy Scan

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    env:
      IMAGE: ${{ secrets.REGISTRY_LOGIN_SERVER }}/cvationintrocontainer:${{ github.sha }}
      # Check version (https://github.com/aquasecurity/trivy/releases)
      TRIVY_VERSION: v0.61.0
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v.4.2.2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2  #v3.10.0

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@9ea583eb67910444b1f64abf338bd2e105a0a93d # v0.2.3
        with:
          version: ${{ env.TRIVY_VERSION }} 

      - name: Cache image layers
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-cache-buildx-${{ github.sha }}
          restore-keys: | 
            ${{ runner.os }}-cache-buildx

      - name: build Docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: app
          tags: ${{ env.IMAGE }}
          load: true
          cache-from: ${{ 'type=gha' || '' }}
          cache-to: ${{ 'type=gha,mode=max' || '' }}

      - name: Trivy scan
        run: |
          # first scan is to generate the output to security tab
          trivy image ${{ env.IMAGE}} --severity 'CRITICAL,HIGH' --format sarif --output trivy-results.sarif --exit-code 0
          # second san is for generating meaningful output in the job logs (using default table output)
          trivy image ${{ env.IMAGE}} --severity 'CRITICAL,HIGH' --exit-code 1

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
        if: failure()
        with:
          sarif_file: 'trivy-results.sarif'